### ISSUE TITLE
Fitness score 0 does not mean Sudoku is solved

### ISSUE THREAD

**Issue by moritzbeck** [ewohltman/genetic-sudoku#4]
You don't check if the 3x3 boxes have every number.

For your default Sudoku puzzle, solutions such as the following have a fitness score of 0, despite not being correctly solved:
```
7 6 4 | 8 5 9 | 3 1 2
9 2 1 | 7 3 4 | 6 5 8
8 5 3 | 6 2 1 | 7 4 9
- - - + - - - + - - -
1 3 5 | 2 9 7 | 4 8 6
2 9 7 | 5 4 6 | 8 3 1
4 7 6 | 3 1 8 | 9 2 5
- - - + - - - + - - -
3 1 8 | 9 7 5 | 2 6 4
6 4 9 | 1 8 2 | 5 7 3
5 8 2 | 4 6 3 | 1 9 7
```
Notice e.g. the two eights in the bottom left box.

**Comment by ewohltman** [comment]
Great catch! I was hoping that counting the duplicates in the rows and columns would be enough, but you proved that is insufficient. Thanks for pointing it out :+1:

**Comment by BartMassey** [comment]
Thanks for catching this!

I have a branch that will fix this, but it looks like @ewohltman is still working on the codebase. When things settle down I'll put in a PR.

With the fitness function fixed things go slower as expected, but not crazily slower. Still works fine for 3×3.

**Comment by ewohltman** [comment]
@BartMassey By all means, please go ahead! My fault for not branching and pushing straight to `main`. I'll wait for you before further pushes.

Thanks!

**Comment by BartMassey** [comment]
Got sidetracked by work. Will poke at this again this evening. Don't want to PR until I have it how I want it…
